export default {
  login: 'rajnishad14',
  id: 43420327,
  node_id: 'MDQ6VXNlcjQzNDIwMzI3',
  avatar_url: 'https://avatars.githubusercontent.com/u/43420327?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/rajnishad14',
  html_url: 'https://github.com/rajnishad14',
  followers_url: 'https://api.github.com/users/rajnishad14/followers',
  following_url:
    'https://api.github.com/users/rajnishad14/following{/other_user}',
  gists_url: 'https://api.github.com/users/rajnishad14/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/rajnishad14/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/rajnishad14/subscriptions',
  organizations_url: 'https://api.github.com/users/rajnishad14/orgs',
  repos_url: 'https://api.github.com/users/rajnishad14/repos',
  events_url: 'https://api.github.com/users/rajnishad14/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/rajnishad14/received_events',
  type: 'User',
  site_admin: false,
  name: 'Raj Kumar Nishad',
  company: 'TCS',
  blog: '',
  location: 'Delhi',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 28,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2018-09-19T18:34:40Z',
  updated_at: '2021-04-05T16:14:18Z',
}
